from tkinter import *

root = Tk()

red="#d62b18"
brown="#876f16"
skin="#fa9644"
bg = "#6185f8"

start_x = 0
start_y = 0
size = 20

screen = Canvas(root, width=320, height=320, bg="#4d2d44")
screen.pack()

row=0 #16 columns that are 1 pixel wide
screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg) #0 is for the first column
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=1
screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=2
screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=3

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=4
screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=5
screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=6

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=7

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=8

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=9

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=10

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=11

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=12

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=skin)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=13

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=red)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=14

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)

row=15

screen.create_rectangle(start_x + 0 * size, start_y + row * size, start_x + 1 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 1 * size, start_y + row * size, start_x + 2 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 2 * size, start_y + row * size, start_x + 3 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 3 * size, start_y + row * size, start_x + 4 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 4 * size, start_y + row * size, start_x + 5 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 5 * size, start_y + row * size, start_x + 6 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 6 * size, start_y + row * size, start_x + 7 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 7 * size, start_y + row * size, start_x + 8 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 8 * size, start_y + row * size, start_x + 9 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 9 * size, start_y + row * size, start_x + 10 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 10 * size, start_y + row * size, start_x + 11 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 11 * size, start_y + row * size, start_x + 12 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 12 * size, start_y + row * size, start_x + 13 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 13 * size, start_y + row * size, start_x + 14 * size, start_y + size + row * size, fill=brown)
screen.create_rectangle(start_x + 14 * size, start_y + row * size, start_x + 15 * size, start_y + size + row * size, fill=bg)
screen.create_rectangle(start_x + 15 * size, start_y + row * size, start_x + 16 * size, start_y + size + row * size, fill=bg)




mainloop()